In [1]:
import numpy as np

In [2]:
np.array([1, 5, 6])

array([1, 5, 6])

In [4]:
example_array = np.array([[34.23, 43.4, 23.03], [8, 234, 43]])
print(example_array)

[[ 34.23  43.4   23.03]
 [  8.   234.    43.  ]]


In [5]:
example_array.ndim  # shows number of dimensions

2

In [6]:
example_array.shape

(2, 3)

In [8]:
example_array.dtype

dtype('float64')

In [12]:
example_array.itemsize

8

In [10]:
another_array = np.array([34, 29, 58], dtype='float64')

In [13]:
another_array.itemsize

8

In [14]:
another_array.nbytes

24

In [15]:
another_array.nbytes == another_array.itemsize * another_array.size

True

### Accessing/Changing Items

In [16]:
array = np.array([[1, 2, 3, 4, 5],
                      [6, 7, 8, 9, 10],
                      [11, 12, 13, 14, 15],
                      [16, 17, 18, 19, 20],
                      [21, 22, 23, 24, 25]])

In [18]:
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [19]:
array[1, 1]

7

In [20]:
array[4, :]

array([21, 22, 23, 24, 25])

In [21]:
array[:, 2]

array([ 3,  8, 13, 18, 23])

In [24]:
array[0, 0:5:2]

array([1, 3, 5])

In [25]:
array[3, 3] = 87

In [26]:
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 87 20]
 [21 22 23 24 25]]


In [31]:
array[3], array[:, 2] = 0, 0

In [32]:
print(array)

[[ 1  2  0  4  5]
 [ 6  7  0  9 10]
 [11 12  0 14 15]
 [ 0  0  0  0  0]
 [21 22  0 24 25]]


### Initializing Different Types

In [36]:
# All 0s matrix
zeros = np.zeros((6, 6))
print(zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [42]:
# All 1s matrix
ones = np.ones((6, 2), dtype='int16')
print(ones)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [41]:
# Matrix filled with a number
example_array = np.full((7, 2), 25)
print(example_array)

[[25 25]
 [25 25]
 [25 25]
 [25 25]
 [25 25]
 [25 25]
 [25 25]]


In [45]:
# Create a matrix with random values
random_array = np.random.randint(5, 8, zeros.shape, dtype='int16')
print(random_array)

[[7 7 5 6 5 6]
 [7 5 7 6 7 6]
 [5 5 6 6 5 6]
 [7 7 7 6 7 7]
 [6 7 6 7 6 6]
 [5 6 5 5 5 5]]


In [48]:
# Identity matrix
print(np.identity(4, dtype='int8'))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [49]:
# Repeating an array
repeatition = np.repeat([[1, 2, 3]], 3)
print(repeatition)

[1 1 1 2 2 2 3 3 3]


### Mathematics

In [50]:
number = np.random.randint(0, 10, (5,5), dtype='int32')

In [51]:
print(number)

[[6 0 5 9 8]
 [3 4 1 3 2]
 [7 7 3 4 8]
 [5 1 0 6 2]
 [1 4 2 8 7]]


In [52]:
number / 10

array([[0.6, 0. , 0.5, 0.9, 0.8],
       [0.3, 0.4, 0.1, 0.3, 0.2],
       [0.7, 0.7, 0.3, 0.4, 0.8],
       [0.5, 0.1, 0. , 0.6, 0.2],
       [0.1, 0.4, 0.2, 0.8, 0.7]])

In [53]:
number * 2

array([[12,  0, 10, 18, 16],
       [ 6,  8,  2,  6,  4],
       [14, 14,  6,  8, 16],
       [10,  2,  0, 12,  4],
       [ 2,  8,  4, 16, 14]], dtype=int32)

In [54]:
number + 10

array([[16, 10, 15, 19, 18],
       [13, 14, 11, 13, 12],
       [17, 17, 13, 14, 18],
       [15, 11, 10, 16, 12],
       [11, 14, 12, 18, 17]], dtype=int32)

In [55]:
number - 10

array([[ -4, -10,  -5,  -1,  -2],
       [ -7,  -6,  -9,  -7,  -8],
       [ -3,  -3,  -7,  -6,  -2],
       [ -5,  -9, -10,  -4,  -8],
       [ -9,  -6,  -8,  -2,  -3]], dtype=int32)

### Linear Algebra

In [59]:
a = np.random.randint(4, 6, (3, 2), dtype='int16')
b = np.random.randint(1, 3, (2, 3), dtype='int16')
print(a)
print()
print(b)

[[5 5]
 [5 5]
 [5 4]]

[[2 1 2]
 [2 2 2]]


In [63]:
np.matmul(b, a)

array([[25, 23],
       [30, 28]], dtype=int16)

In [67]:
# Calculate determinant
c = np.random.randint(1, 10, (3, 3), dtype='int16')
print(c)
np.linalg.det(c)

[[4 2 4]
 [1 7 5]
 [9 2 4]]


-90.0

They are so many things that you can do that is available in numpy's documentation.

### Statistics

In [70]:
d = np.array([[3, 5, 6], [1, 4, 2]])
print(d)

[[3 5 6]
 [1 4 2]]


In [71]:
np.min(d)

1

In [72]:
np.max(d)

6

In [73]:
np.sum(d)

21

### Reorganizing

In [74]:
e = np.random.randint(1, 10, (2, 4), dtype='int16')
print(e)

[[2 4 5 8]
 [1 8 5 3]]


In [76]:
print(e.reshape(1, 8))

[[2 4 5 8 1 8 5 3]]


In [77]:
print(e.reshape(4, 2))

[[2 4]
 [5 8]
 [1 8]
 [5 3]]


In [81]:
# Vertically stacking
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
print(np.vstack([v1, v2]))

[[1 2 3 4]
 [5 6 7 8]]


You can use `hstack()` and many other functions. Since they are not used a lot in daily basis, they are not covered here.