In [1]:
import numpy as np

In [2]:
array = np.random.randint(1, 10, (3, 3), dtype='int8')

In [3]:
array

array([[3, 5, 4],
       [4, 9, 2],
       [8, 8, 6]], dtype=int8)

In [4]:
np.unique(array)

array([2, 3, 4, 5, 6, 8, 9], dtype=int8)

# Variance
The measure of the average degree to which each number is defferent from the mean value.
Higher variance means wider range of numbers and the opposite.

In [5]:
print(np.var(array), array.var())

5.3580246913580245 5.3580246913580245


# Standard Deviation
The measure of how spread out are the numbers from the mean value.

In [6]:
print(np.std(array), array.std())

2.3147407395555177 2.3147407395555177


In [7]:
np.sqrt(np.var(array))

2.3147407395555177

### A few examples of `var` and `std`

In [8]:
high_var = np.array([2, 56, 78, 1200, 5600])
low_var = np.array([1, 2, 3, 4, 5])

In [9]:
print(high_var.var(), low_var.var())

4637520.96 2.0


In [10]:
print(high_var.std(), low_var.std())

2153.490413259367 1.4142135623730951


In [11]:
print(high_var.mean(), low_var.mean())

1387.2 3.0


# Reshaping and Transposing

In [14]:
example_array = np.random.randint(1, 10, (2, 8), dtype='int8')

In [15]:
example_array

array([[1, 8, 9, 7, 1, 8, 9, 2],
       [7, 3, 1, 3, 2, 1, 7, 5]], dtype=int8)

In [16]:
example_array.reshape(4, 4)

array([[1, 8, 9, 7],
       [1, 8, 9, 2],
       [7, 3, 1, 3],
       [2, 1, 7, 5]], dtype=int8)

# Math Product

In [24]:
# hadamard product
a, b = np.random.randint(1, 10, (3, 3)), np.random.randint(1, 10, (3, 3))

In [25]:
print(a)

[[6 5 7]
 [9 4 4]
 [7 8 4]]


In [26]:
print(b)

[[8 6 4]
 [1 8 6]
 [8 9 4]]


In [27]:
a * b

array([[48, 30, 28],
       [ 9, 32, 24],
       [56, 72, 16]])

In [28]:
np.dot(a, b)

array([[109, 139,  82],
       [108, 122,  76],
       [ 96, 142,  92]])

Let's have an example of dot product using with transposing.

In [31]:
x, y = np.random.randint(1, 10, (5, 3)), np.random.randint(1, 10, (5, 3))
print(x, y, sep='\n\n')

[[1 5 2]
 [7 9 7]
 [6 7 5]
 [5 7 6]
 [7 1 8]]

[[9 2 5]
 [3 9 6]
 [9 6 9]
 [4 2 9]
 [2 8 7]]


In [32]:
x.shape

(5, 3)

In [34]:
x = x.T

In [35]:
x.shape

(3, 5)

In [36]:
x

array([[1, 7, 6, 5, 7],
       [5, 9, 7, 7, 1],
       [2, 7, 5, 6, 8]])

In [37]:
np.dot(x, y)

array([[118, 167, 195],
       [165, 155, 212],
       [124, 173, 207]])